Candidate.create!(name: "Jeff Sessions", office: "US Senate", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "Parker Griffith", office: "Governor", party_affiliation: "Democratic", zip_id: "1" )
Candidate.create!(name: "Robert Bentley", office: "Governor", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "James C. Fields Jr.", office: "Lt. Governor", party_affiliation: "Democratic", zip_id: "1" )
Candidate.create!(name: "Kay Ivey", office: "Lt. Governor", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "Joe Hubbard", office: "Attorney General", party_affiliation: "Democratic", zip_id: "1" )
Candidate.create!(name: "Luther Strange", office: "Attorney General", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "Miranda Karrine Joseph", office: "Auditor", party_affiliation: "Democratic", zip_id: "1" )
Candidate.create!(name: "Jim Zeigler", office: "Auditor", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "Doug "New Blue" Smith", office: "Commissioner of Agriculture", party_affiliation: "Democratic", zip_id: "1" )
Candidate.create!(name: "John McMillan", office: "Commissioner of Agriculture", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "Lula Albert-Kaigler", office: "Secretary of State", party_affiliation: "Democratic", zip_id: "1" )
Candidate.create!(name: "John Merill", office: "Secretary of State", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "Young Boozer", office: "Treasurer", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "Greg Shaw", office: "Associate Justice of the Supreme Court, Place No. 1", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "Jeremy H. Oden", office: "Public Service Commission - Place 1", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "Chris "Chip" Beeker, Jr.", office: "Public Service Commission - Place 2", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "Terry Dunn", office: "Public Service Commission - Place 2", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "William C. "Bill" Thompson", office: "Court of Civil Appeals, Place 1", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "Scott Donaldson", office: "Court of Civil Appeals, Place 2", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "Mary B. Windom", office: "Court of Criminal Appeals, Place 1", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "Beth Kellum", office: "Court of Criminal Appeals, Place 2", party_affiliation: "Republican", zip_id: "1" )
Candidate.create!(name: "Jeff Sessions", office: "US Senate", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "Parker Griffith", office: "Governor", party_affiliation: "Democratic", zip_id: "2" )
Candidate.create!(name: "Robert Bentley", office: "Governor", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "James C. Fields Jr.", office: "Lt. Governor", party_affiliation: "Democratic", zip_id: "2" )
Candidate.create!(name: "Kay Ivey", office: "Lt. Governor", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "Joe Hubbard", office: "Attorney General", party_affiliation: "Democratic", zip_id: "2" )
Candidate.create!(name: "Luther Strange", office: "Attorney General", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "Miranda Karrine Joseph", office: "Auditor", party_affiliation: "Democratic", zip_id: "2" )
Candidate.create!(name: "Jim Zeigler", office: "Auditor", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "Doug "New Blue" Smith", office: "Commissioner of Agriculture", party_affiliation: "Democratic", zip_id: "2" )
Candidate.create!(name: "John McMillan", office: "Commissioner of Agriculture", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "Lula Albert-Kaigler", office: "Secretary of State", party_affiliation: "Democratic", zip_id: "2" )
Candidate.create!(name: "John Merill", office: "Secretary of State", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "Young Boozer", office: "Treasurer", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "Greg Shaw", office: "Associate Justice of the Supreme Court, Place No. 1", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "Jeremy H. Oden", office: "Public Service Commission - Place 1", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "Chris "Chip" Beeker, Jr.", office: "Public Service Commission - Place 2", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "Terry Dunn", office: "Public Service Commission - Place 2", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "William C. "Bill" Thompson", office: "Court of Civil Appeals, Place 1", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "Scott Donaldson", office: "Court of Civil Appeals, Place 2", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "Mary B. Windom", office: "Court of Criminal Appeals, Place 1", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "Beth Kellum", office: "Court of Criminal Appeals, Place 2", party_affiliation: "Republican", zip_id: "2" )
Candidate.create!(name: "Jeff Sessions", office: "US Senate", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "Parker Griffith", office: "Governor", party_affiliation: "Democratic", zip_id: "3" )
Candidate.create!(name: "Robert Bentley", office: "Governor", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "James C. Fields Jr.", office: "Lt. Governor", party_affiliation: "Democratic", zip_id: "3" )
Candidate.create!(name: "Kay Ivey", office: "Lt. Governor", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "Joe Hubbard", office: "Attorney General", party_affiliation: "Democratic", zip_id: "3" )
Candidate.create!(name: "Luther Strange", office: "Attorney General", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "Miranda Karrine Joseph", office: "Auditor", party_affiliation: "Democratic", zip_id: "3" )
Candidate.create!(name: "Jim Zeigler", office: "Auditor", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "Doug "New Blue" Smith", office: "Commissioner of Agriculture", party_affiliation: "Democratic", zip_id: "3" )
Candidate.create!(name: "John McMillan", office: "Commissioner of Agriculture", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "Lula Albert-Kaigler", office: "Secretary of State", party_affiliation: "Democratic", zip_id: "3" )
Candidate.create!(name: "John Merill", office: "Secretary of State", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "Young Boozer", office: "Treasurer", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "Greg Shaw", office: "Associate Justice of the Supreme Court, Place No. 1", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "Jeremy H. Oden", office: "Public Service Commission - Place 1", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "Chris "Chip" Beeker, Jr.", office: "Public Service Commission - Place 2", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "Terry Dunn", office: "Public Service Commission - Place 2", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "William C. "Bill" Thompson", office: "Court of Civil Appeals, Place 1", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "Scott Donaldson", office: "Court of Civil Appeals, Place 2", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "Mary B. Windom", office: "Court of Criminal Appeals, Place 1", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "Beth Kellum", office: "Court of Criminal Appeals, Place 2", party_affiliation: "Republican", zip_id: "3" )
Candidate.create!(name: "Jeff Sessions", office: "US Senate", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "Parker Griffith", office: "Governor", party_affiliation: "Democratic", zip_id: "4" )
Candidate.create!(name: "Robert Bentley", office: "Governor", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "James C. Fields Jr.", office: "Lt. Governor", party_affiliation: "Democratic", zip_id: "4" )
Candidate.create!(name: "Kay Ivey", office: "Lt. Governor", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "Joe Hubbard", office: "Attorney General", party_affiliation: "Democratic", zip_id: "4" )
Candidate.create!(name: "Luther Strange", office: "Attorney General", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "Miranda Karrine Joseph", office: "Auditor", party_affiliation: "Democratic", zip_id: "4" )
Candidate.create!(name: "Jim Zeigler", office: "Auditor", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "Doug "New Blue" Smith", office: "Commissioner of Agriculture", party_affiliation: "Democratic", zip_id: "4" )
Candidate.create!(name: "John McMillan", office: "Commissioner of Agriculture", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "Lula Albert-Kaigler", office: "Secretary of State", party_affiliation: "Democratic", zip_id: "4" )
Candidate.create!(name: "John Merill", office: "Secretary of State", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "Young Boozer", office: "Treasurer", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "Greg Shaw", office: "Associate Justice of the Supreme Court, Place No. 1", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "Jeremy H. Oden", office: "Public Service Commission - Place 1", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "Chris "Chip" Beeker, Jr.", office: "Public Service Commission - Place 2", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "Terry Dunn", office: "Public Service Commission - Place 2", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "William C. "Bill" Thompson", office: "Court of Civil Appeals, Place 1", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "Scott Donaldson", office: "Court of Civil Appeals, Place 2", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "Mary B. Windom", office: "Court of Criminal Appeals, Place 1", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "Beth Kellum", office: "Court of Criminal Appeals, Place 2", party_affiliation: "Republican", zip_id: "4" )
Candidate.create!(name: "Jeff Sessions", office: "US Senate", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "Parker Griffith", office: "Governor", party_affiliation: "Democratic", zip_id: "5" )
Candidate.create!(name: "Robert Bentley", office: "Governor", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "James C. Fields Jr.", office: "Lt. Governor", party_affiliation: "Democratic", zip_id: "5" )
Candidate.create!(name: "Kay Ivey", office: "Lt. Governor", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "Joe Hubbard", office: "Attorney General", party_affiliation: "Democratic", zip_id: "5" )
Candidate.create!(name: "Luther Strange", office: "Attorney General", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "Miranda Karrine Joseph", office: "Auditor", party_affiliation: "Democratic", zip_id: "5" )
Candidate.create!(name: "Jim Zeigler", office: "Auditor", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "Doug "New Blue" Smith", office: "Commissioner of Agriculture", party_affiliation: "Democratic", zip_id: "5" )
Candidate.create!(name: "John McMillan", office: "Commissioner of Agriculture", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "Lula Albert-Kaigler", office: "Secretary of State", party_affiliation: "Democratic", zip_id: "5" )
Candidate.create!(name: "John Merill", office: "Secretary of State", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "Young Boozer", office: "Treasurer", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "Greg Shaw", office: "Associate Justice of the Supreme Court, Place No. 1", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "Jeremy H. Oden", office: "Public Service Commission - Place 1", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "Chris "Chip" Beeker, Jr.", office: "Public Service Commission - Place 2", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "Terry Dunn", office: "Public Service Commission - Place 2", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "William C. "Bill" Thompson", office: "Court of Civil Appeals, Place 1", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "Scott Donaldson", office: "Court of Civil Appeals, Place 2", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "Mary B. Windom", office: "Court of Criminal Appeals, Place 1", party_affiliation: "Republican", zip_id: "5" )
Candidate.create!(name: "Beth Kellum", office: "Court of Criminal Appeals, Place 2", party_affiliation: "Republican", zip_id: "5" )
Zipcode.create!(zip: "35118")
Zipcode.create!(zip: "35119")
Zipcode.create!(zip: "35120")
Zipcode.create!(zip: "35121")
Zipcode.create!(zip: "35123")
